# AMLT Batch Inference for Flux2Klein - ALL checkpoints, multiple CFG values
# Single job, runs all checkpoints sequentially with try-except
# CFG: 4.0 and 3.5, 50 steps each
# amlt run amlt/260129/run_fluxklein_inference_batch.yaml -y
target:
  name: msrresrchlab
  service: sing
  workspace_name: mcgvisionflowws

environment:
  image: amlt-sing/acpt-torch2.7.1-py3.10-cuda12.6-ubuntu22.04

storage:
  data:
    container_name: yuxuanluo
    mount_dir: /mnt/data
    storage_account_name: mcgvisionflowsa

code:
  local_dir: /home/v-yuxluo/WORK_local/ArXivQwenImage

description: 0129_fluxklein_batch_inference_all_ckpts

jobs:
- name: batch_inference_all
  process_count_per_node: 1
  sku: 1x32G4-V100
  command:
  # Install system dependencies
  - sudo apt-get update
  - sudo apt-get install -y libglib2.0-0
  - sudo apt-get install -y libgl1
  
  # Install Python dependencies
  - pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
  - pip install git+https://github.com/huggingface/diffusers
  - pip install transformers==4.55.0 accelerate protobuf wandb #4.51.3不支持dict的config传入
  - pip install opencv-python pandas pyarrow datasets ftfy sentencepiece einops scikit-learn timm==0.9.2 mmengine tqdm
  - pip install bitsandbytes>=0.43.0 peft pydantic ray[train] prodigyopt
  
  # Run batch inference: all checkpoints from 28500 to 16000, step 1000
  # Multiple CFG values: 4.0, 3.5
  - accelerate launch --num_processes=4
    test/test_flux2klein_batch_inference.py
    --config configs/260124/flux2klein_fulltune_50000_amlt_ga4.py
    --checkpoint_base /mnt/data/experiments/260124_fluxklein9B_fulltune_GA4
    --output_base /mnt/data/inference_results/260124_initial_try_flux2klein9Bbase_fulltune
    --num_inference_steps 50
    --guidance_scales "4.0,3.5"
    --start_step 28500
    --min_step 16000
    --step_interval 1000
    --seed 42
  
  - echo "=== Batch inference completed! ==="
  
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/e56674e8-8a8b-4559-8a24-4149e2e4565b/resourcegroups/mcg_vision_flow_rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mcgvisionflowid
  sla_tier: basic
  execution_mode: basic
  priority: high
  tags: ["Project_Name:VisionFlow"]
